package com.omniwrench.ai;

import java.time.Instant;
import java.util.Objects;

/**
 * Strongly typed AI model response.
 *
 * <p>Wraps the raw output with metadata including latency, token counts,
 * and provider identifiers for observability (ADR-0014).
 *
 * @param <T> the MediaType classification of the originating request
 */
public final class ModelResponse<T extends MediaType> {

    /** The raw text or serialized content of the response. */
    private final String content;
    /** The media type mirrored from the request. */
    private final T mediaType;
    /** Number of input tokens consumed by this request. */
    private final int inputTokens;
    /** Number of output tokens generated by this request. */
    private final int outputTokens;
    /** The model name as reported by the backend. */
    private final String resolvedModel;
    /** The timestamp when this response was received. */
    private final Instant timestamp;

    /**
     * Constructs a model response with full validation.
     *
     * @param content the response content, must not be null
     * @param mediaType the media type, must not be null
     * @param inputTokens the number of input tokens
     * @param outputTokens the number of output tokens
     * @param resolvedModel the resolved model name, must not be null
     * @param timestamp the response timestamp, must not be null
     */
    public ModelResponse(
            final String content,
            final T mediaType,
            final int inputTokens,
            final int outputTokens,
            final String resolvedModel,
            final Instant timestamp) {
        this.content = Objects.requireNonNull(content, "content must not be null");
        this.mediaType = Objects.requireNonNull(mediaType, "mediaType must not be null");
        this.inputTokens = inputTokens;
        this.outputTokens = outputTokens;
        this.resolvedModel = Objects.requireNonNull(resolvedModel, "resolvedModel must not be null");
        this.timestamp = Objects.requireNonNull(timestamp, "timestamp must not be null");
    }

    /** Returns the response content. */
    public String getContent() { return content; }
    /** Returns the media type. */
    public T getMediaType() { return mediaType; }
    /** Returns input token count. */
    public int getInputTokens() { return inputTokens; }
    /** Returns output token count. */
    public int getOutputTokens() { return outputTokens; }
    /** Returns the resolved model identifier. */
    public String getResolvedModel() { return resolvedModel; }
    /** Returns the response timestamp. */
    public Instant getTimestamp() { return timestamp; }
}
