package com.omniwrench.ai;

import java.time.Instant;
import java.util.Objects;

/**
 * Strongly typed AI model response.
 *
 * <p>Wraps the raw output with metadata including latency, token counts,
 * and provider identifiers for observability (ADR-0014).
 *
 * Traceability:
 * - Requirement: REQ-00040 (Custom Multi-Modal AI Adapter SPI), REQ-00077 (OpenTelemetry Distributed Tracing)
 * - Feature: FR-00011 (Multi-Modal Typed AI Abstraction), FR-00033 (OpenTelemetry Distributed Tracing)
 * - Use Case: UC-00001 (Interactive TUI Pair Programming)
 * - ADR: ADR-0014 (OpenTelemetry Distributed Tracing), ADR-0015 (Future-Proof Multi-Modal SPI)
 *
 * @param <T> the MediaType classification of the originating request
 */
public final class ModelResponse<T extends MediaType> {

    /** The raw text or serialized content of the response. */
    private final String content;
    /** The media type mirrored from the request. */
    private final T mediaType;
    /** Number of input tokens consumed by this request. */
    private final int inputTokens;
    /** Number of output tokens generated by this request. */
    private final int outputTokens;
    /** The model name as reported by the backend. */
    private final String resolvedModel;
    /** The timestamp when this response was received. */
    private final Instant timestamp;

    /**
     * Constructs a model response with full validation.
     *
     * @param contentVal the response content, must not be null
     * @param mediaTypeVal the media type, must not be null
     * @param inputTokensVal the number of input tokens
     * @param outputTokensVal the number of output tokens
     * @param resolvedModelVal the resolved model name, must not be null
     * @param timestampVal the response timestamp, must not be null
     */
    public ModelResponse(
            final String contentVal,
            final T mediaTypeVal,
            final int inputTokensVal,
            final int outputTokensVal,
            final String resolvedModelVal,
            final Instant timestampVal) {
        this.content = Objects.requireNonNull(contentVal, "content must not be null");
        this.mediaType = Objects.requireNonNull(mediaTypeVal, "mediaType must not be null");
        this.inputTokens = inputTokensVal;
        this.outputTokens = outputTokensVal;
        this.resolvedModel = Objects.requireNonNull(resolvedModelVal, "resolvedModel must not be null");
        this.timestamp = Objects.requireNonNull(timestampVal, "timestamp must not be null");
    }

    /**
     * Returns the response content.
     *
     * @return the response content
     */
    public String getContent() {
        return content;
    }

    /**
     * Returns the media type.
     *
     * @return the media type
     */
    public T getMediaType() {
        return mediaType;
    }

    /**
     * Returns input token count.
     *
     * @return number of input tokens
     */
    public int getInputTokens() {
        return inputTokens;
    }

    /**
     * Returns output token count.
     *
     * @return number of output tokens
     */
    public int getOutputTokens() {
        return outputTokens;
    }

    /**
     * Returns the resolved model identifier.
     *
     * @return resolved model name
     */
    public String getResolvedModel() {
        return resolvedModel;
    }

    /**
     * Returns the response timestamp.
     *
     * @return response timestamp
     */
    public Instant getTimestamp() {
        return timestamp;
    }
}
