package com.omniwrench.ai;

import reactor.core.publisher.Flux;

/**
 * Extension of {@link BackendAdapter} supporting reactive streaming of output tokens.
 *
 * <p>Enables real-time token emission to TUI renderers and WebSocket clients as tokens
 * are generated by the underlying model inference engine (ADR-0015).
 *
 * Traceability:
 * - Requirement: REQ-00040 (Custom Multi-Modal AI Adapter SPI), REQ-00090 (Embedded llama.cpp Local LLM Backend Plugin)
 * - Feature: FR-00011 (Multi-Modal Typed AI Abstraction), FR-00012 (Universal Pluggable AI Adapters)
 * - Use Case: UC-00001 (Interactive TUI Pair Programming)
 * - Task: TSK-20260822-015 (In-Process Embedded llama.cpp Engine)
 * - ADR: ADR-0015 (Future-Proof Multi-Modal SPI), ADR-0049 (llama.cpp Embedded Inference Engine)
 *
 * @param <T> the MediaType this adapter processes
 */
public interface StreamingBackendAdapter<T extends MediaType> extends BackendAdapter<T> {

    /**
     * Executes a model request in streaming mode, emitting tokens reactively via a Flux.
     *
     * @param request the request to execute, must not be null
     * @return a Flux emitting token text chunks as they are generated
     * @throws BackendException if initialization or inference fails
     */
    Flux<String> executeStream(ModelRequest<T> request);
}
